Company.Route2.PL/Controllers/DepartementController.cs
using AutoMapper;
using Company.Route2.BLL.Interfaces;
using Company.Route2.BLL.UnitOfWork;
using Company.Route2.DAL.Models;
using Company.Route2.PL.ModelViews;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace Company.Route2.PL.Controllers
{
    [Authorize]

    public class DepartementController : Controller
    {
        // private IDepartementRepository _departementRepository;
         private readonly IMapper _mapper;
        private readonly IUnitOfWork _unitOfWork;

        public DepartementController(
           // IDepartementRepository departementRepository,
             IMapper mapper
            ,IUnitOfWork _unitOfWork)
        {
            // _departementRepository = departementRepository;
            this._mapper = mapper;
           this. _unitOfWork = _unitOfWork;
        }

        [HttpGet]
        public async Task< IActionResult> Index()
        {
            var departements = await _unitOfWork.DepartementRepository.GetAllAsync();
            // 1 viewdata
            ViewData["message"] = "Thats Our Great Departement ";
           var result= _mapper.Map<IEnumerable<DepartmentViewModel>>(departements);
            return View(result);
        }
        [HttpGet]

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public async Task< IActionResult> Create(DepartmentViewModel model)
        {
            if (ModelState.IsValid)
            {
                //Departement departement = new Departement()
                //{
                //    Id = model.Id,
                //    Name = model.Name,
                //    Code = model.Code,
                //    DateOfCreation = model.DateOfCreation,
                //    Employees = model.Employees,
                //};

                var result = _mapper.Map<Departement>(model);

                await _unitOfWork.DepartementRepository.CreateAsync(result);
                var count =  await _unitOfWork.SaveChangesAsync();


                if (count > 0)
                {
                    TempData["message4"] = "Departement created sucessful";
                }
                else
                {
                    TempData["message4"] = "Departement not created ";
                }

                return RedirectToAction("Index");
            }
            return View(model);
        }
        [HttpGet]

        public async Task<IActionResult> Detials(int? id, string viewName= "Detials")
        {
            if (id is null) return BadRequest();

            var model = await _unitOfWork.DepartementRepository.GetAsync(id);


            //DepartmentViewModel departement = new DepartmentViewModel()
            // {
            //     Id = model.Id,
            //     Name = model.Name,
            //     Code = model.Code,
            //     DateOfCreation = model.DateOfCreation,
            //     Employees = model.Employees,
            // };
            var result = _mapper.Map<DepartmentViewModel>(model);

            if (result is null) return NotFound();
            return View(result);

        }

        [HttpGet]
        public Task<IActionResult> Edit(int? id)
        {

            return Detials(id, "Edit");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] int? id ,DepartmentViewModel model)
        {

             if (id != model.Id) return BadRequest();

             if (ModelState.IsValid)

            {   
               

                //   Departement departement = new Departement()
                //   {
                //       Id = model.Id,
                //       Name = model.Name,
                //       Code = model.Code,
                //       DateOfCreation = model.DateOfCreation,
                //       Employees = model.Employees,
                //  };

                var result = _mapper.Map<Departement>(model);


                _unitOfWork.DepartementRepository.Update(result);
                var count = await _unitOfWork.SaveChangesAsync();

                 if (count > 0)
                 {
                     return RedirectToAction("Index");
                 }

             }

             return View(model);
        }


        [HttpGet]

        public Task<IActionResult> Delete(int? id)
        {
            return Detials(id, "Delete");

        }

        public async Task<IActionResult> Delete( [FromRoute] int? id , DepartmentViewModel model)
        {
            if (id != model.Id) return BadRequest();

            //Departement departement = new Departement()
            //{
            //    Id = model.Id,
            //    Name = model.Name,
            //    Code = model.Code,
            //    DateOfCreation = model.DateOfCreation,
            //    Employees = model.Employees,
            //};

            var result = _mapper.Map<Departement>(model);

            _unitOfWork.DepartementRepository.Delete(result);
            var count= await _unitOfWork.SaveChangesAsync();   

            if (count == 0) return View();
            return RedirectToAction("Index");
        }

    }
}

Company.Route2.PL/Controllers/RoleController.cs
using Company.Route2.DAL.Models;
using Company.Route2.PL.ModelViews;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.ModelBinding;
using Microsoft.EntityFrameworkCore;

namespace Company.Route2.PL.Controllers
{
    [Authorize(Roles="admin")]

    public class RoleController  : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public RoleController(UserManager<ApplicationUser> _userManager, RoleManager<IdentityRole> _roleManager)
        {
            this._userManager = _userManager;
            this._roleManager = _roleManager;
        }

        public async Task<IActionResult> Index(string? searchKeyWord)
        {
            var role = Enumerable.Empty<RoleViewModel>();

            if (string.IsNullOrEmpty(searchKeyWord))
            {
                role =  _roleManager.Roles.Select(u => new RoleViewModel()
                {
                    Id = u.Id,
                    Name = u.Name
                }).ToList();
            }
            else
            {
                role =  _roleManager.Roles.Where(u => u.Name
                                                           .ToLower()
                                                           .Contains(searchKeyWord.ToLower()))
                                                           .Select(u => new RoleViewModel()
                                                           {
                                                               Id = u.Id,
                                                               Name = u.Name
                                                           }).ToList();


            }
            return View(role);
        }
        [HttpGet]
        public IActionResult Create()
        {
            return View();

    }
        [HttpGet]
        public async Task< IActionResult> AddOrRemoveRole(string? Id)
        {
            if (Id is null) return BadRequest();
            var RoleFromDB = await _roleManager.FindByIdAsync(Id);
            if (RoleFromDB is null)
                return NotFound();
            TempData["RoleId"] = RoleFromDB.Id;

            var Users = await _userManager.Users.ToListAsync();
            var Result = new List<UserInRoleViewModel>();
            foreach(var User in Users)
            {
                var userRoleViewModel = new UserInRoleViewModel()
                {
                    Id = User.Id,
                    Name = User.UserName,
                };
                if(await _userManager.IsInRoleAsync(User, RoleFromDB.Name))
                {
                    userRoleViewModel.IsSelected=true;  
                }else if(! await _userManager.IsInRoleAsync(User, RoleFromDB.Name))
                {
                    userRoleViewModel.IsSelected = false;
                }

                Result.Add(userRoleViewModel);
            }
            return View(Result);

        }
        [HttpPost]
        public async Task<IActionResult> AddOrRemoveRole(string? Id, List< UserInRoleViewModel> Users)
        {
            if (Id is null) return BadRequest();
            var RoleFromDB = await _roleManager.FindByIdAsync(Id);
            if (RoleFromDB is null)
                return NotFound();
            var result = new IdentityResult();
            if (ModelState.IsValid)
            {
                foreach(var user in Users)
                {
                    var userFromDb= await _userManager.FindByIdAsync(user.Id);
                    if(userFromDb is null)
                        return NotFound();
                    if (user.IsSelected && ! await _userManager.IsInRoleAsync(userFromDb,RoleFromDB.Name))
                    {
                       result=  await _userManager.AddToRoleAsync(userFromDb, RoleFromDB.Name);
                        
                    }else if (!user.IsSelected && await _userManager.IsInRoleAsync(userFromDb, RoleFromDB.Name))
                    {
                        result = await _userManager.RemoveFromRoleAsync(userFromDb, RoleFromDB.Name);
                    }
                }
                return RedirectToAction("Edit", new { Id = Id });

            }
            return View(Users);

        }


        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create( RoleViewModel model)
        {

            if (ModelState.IsValid)
            {
                var role = new IdentityRole()
                {
                   Name = model.Name
                };
               
                var result = await _roleManager.CreateAsync(role);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

            }
            return View(model);
        }
        // Details
        
        public async Task<IActionResult> Detials(string? id, string ViewName = "Detials")
        {
            if (string.IsNullOrEmpty(id))
                return BadRequest();
            var RoleFromDB = await _roleManager.FindByIdAsync(id);
            if (RoleFromDB is null)
                return NotFound();
            var role = new RoleViewModel()
            {
                Id = RoleFromDB.Id,
                Name = RoleFromDB.Name

            };
            return View(role);
        }

        public Task<IActionResult> Edit(string? id)
        {

            return Detials(id, "Edit");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, RoleViewModel model)
        {

            if (id != model.Id) return BadRequest();
            if (ModelState.IsValid)
            {
                var RoleFromDB = await _roleManager.FindByIdAsync(id);
                if (RoleFromDB is null)
                    return NotFound();

                RoleFromDB.Name = model.Name;

                var result = await _roleManager.UpdateAsync(RoleFromDB);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

            }
            return View(model);
        }
        [HttpGet]

        public Task<IActionResult> Delete(string? id)
        {
            return Detials(id, "Delete");
        }


        public async Task<IActionResult> Delete([FromRoute] string? id, RoleViewModel model)
        {

            if (id != model.Id) return BadRequest();
            var RoleViewModel = await _roleManager.FindByIdAsync(id);
            if (RoleViewModel is null)
                return NotFound();

            var result = await _roleManager.DeleteAsync(RoleViewModel);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }

            return View(model);
        }


    }
}

Company.Route2.PL/Controllers/UserController.cs
using AutoMapper;
using Company.Route2.DAL.Models;
using Company.Route2.PL.Helper;
using Company.Route2.PL.ModelViews;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using Microsoft.VisualStudio.Web.CodeGenerators.Mvc.Templates.Blazor;

namespace Company.Route2.PL.Controllers
{
    [Authorize]

    public class UserController : Controller
	{
		private readonly UserManager<ApplicationUser> _userManager;
		private readonly SignInManager<ApplicationUser> _signInManager;

		public UserController( UserManager<ApplicationUser> _userManager,SignInManager<ApplicationUser> _signInManager) 
		{
			this._userManager = _userManager;
			this._signInManager = _signInManager;
		}	

		public async Task< IActionResult> Index(string? searchKeyWord)
		{
			var user = Enumerable.Empty<UserViewModel>();

			if(string.IsNullOrEmpty(searchKeyWord))
			{
				user = await _userManager.Users.Select(u => new UserViewModel()
				{
					Id=u.Id,	
					Fname = u.Fname,
					Lname = u.Lname,
					Email = u.Email,
					Roles =  _userManager.GetRolesAsync(u).Result
				}).ToListAsync();
			}
			else
			{
				user= await _userManager.Users.Where(u=>u.Email
			                                               .ToLower()
			                                               .Contains(searchKeyWord.ToLower()))
			                                               .Select(u => new UserViewModel()
			                                               {
			                                               		Fname = u.Fname,
			                                               		Lname = u.Lname,
			                                               		Email = u.Email,
			                                               		Roles = _userManager.GetRolesAsync(u).Result
			                                               }).ToListAsync();


			}
			return View(user);	
		}


		// Details
		public async Task< IActionResult> Detials(string? id, string ViewName= "Detials")
		{
			if (string.IsNullOrEmpty(id))
				return BadRequest();
			var userFromDB = await _userManager.FindByIdAsync(id);
			if (userFromDB is null)
				return NotFound();
			var user = new UserViewModel()
			{
				Id = userFromDB.Id,
				Fname = userFromDB.Fname,
				Lname = userFromDB.Lname,
				Email = userFromDB.Email,
				Roles = _userManager.GetRolesAsync(userFromDB).Result

			};

            return View(user);
		}

        public Task<IActionResult> Edit(string? id)
        {

            return Detials(id, "Edit");
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit([FromRoute] string id, UserViewModel model)
        {

            if (id != model.Id) return BadRequest();
            if (ModelState.IsValid)
            {


                var userFromDB = await _userManager.FindByIdAsync(id);
                if (userFromDB is null)
                    return NotFound();

                    userFromDB.Fname = model.Fname;
                    userFromDB.Lname = model.Lname;
                    userFromDB.Email = model.Email;


                var result= await _userManager.UpdateAsync(userFromDB);
                if (result.Succeeded)
                {
                    return RedirectToAction("Index");
                }

            }
            return View(model);
        }
        [HttpGet]

        public Task<IActionResult> Delete(string? id)
        {
            return Detials(id, "Delete");
        }


        public async Task<IActionResult> Delete([FromRoute] string? id, UserViewModel model)
        {

            if (id != model.Id) return BadRequest();
            var userFromDB = await _userManager.FindByIdAsync(id);
            if (userFromDB is null)
                return NotFound();

            var result = await _userManager.DeleteAsync(userFromDB);
            if (result.Succeeded)
            {
                return RedirectToAction("Index");
            }

            return View(model);
        }
    }
}

Company.Route2.PL/Views/Shared/IndexPartialView.cshtml
@model string
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<td><a asp-action="Detials" asp-route-Id="@Model" class="btn btn-warning">Detials</a></td>
<td><a asp-action="Edit" asp-route-Id="@Model" class="btn btn-danger">Edit</a></td>
<td><a asp-action="Delete" asp-route-Id="@Model" class="btn btn-dark">Delete</a></td>

Company.Route2.PL/Views/Shared/_AuthLayout.cshtml
<!--
Author: Colorlib
Author URL: https://colorlib.com
License: Creative Commons Attribution 3.0 Unported
License URL: http://creativecommons.org/licenses/by/3.0/
-->
<!DOCTYPE html>
<html>
<head>
	<title> SignUp Form</title>
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<script type="application/x-javascript"> addEventListener("load", function() { setTimeout(hideURLbar, 0); }, false); function hideURLbar(){ window.scrollTo(0,1); } </script>
	<!-- Custom Theme files -->
	
	<link href="~/css/StyleSheet.css" rel="stylesheet" type="text/css" media="all" />
	<link href="~/lib/bootstrap/dist/css/bootstrap.min.css" rel="stylesheet" type="text/css" media="all" />
	<!-- //Custom Theme files -->
	<!-- web font -->
	<link href="//fonts.googleapis.com/css?family=Roboto:300,300i,400,400i,700,700i" rel="stylesheet">
	<!-- //web font -->
</head>
<body>
	<!-- main -->
	<div class="main-w3layouts wrapper">
		@RenderBody()
		<!-- copyright -->
		<div class="colorlibcopy-agile">
			<p>© 2018 Colorlib Signup Form. All rights reserved | Design by <a href="https://colorlib.com/" target="_blank">Colorlib</a></p>
		</div>
		<!-- //copyright -->
		<ul class="colorlib-bubbles">
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
			<li></li>
		</ul>
	</div>
	<!-- //main -->
</body>
</html>

Company.Route2.PL/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Company.Route2.PL</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Company.Route2.PL.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Company.Route2.PL</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Departement" asp-action="Index">Departement</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employee" asp-action="Index">Employee</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="Index">Users</a>
                        </li>
                         <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Role" asp-action="Index">Roles</a>
                        </li>
                    </ul>
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark btn btn-warning" asp-controller="Account" asp-action="SignOut">Logout</a>
                        </li>
                        
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2024 - Company.Route2.PL - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("x", required: false)
</body>
</html>